#-------------------------------------------------------------------
#          D - F L A T   M A K E F I L E - Turbo C 2.0
#-------------------------------------------------------------------

all : memopad.exe huffc.exe

#------------------------------------------------
# NOTE: Set DRIVE to match where you installed your compiler
#------------------------------------------------
DRIVE = F:\COMPILER
#-------------------------------------------------------------------
#  Delete the TESTING macro to eliminate the D-Flat Log and the Reload
#  Help file selection on the Help menu
#-------------------------------------------------------------------
TESTING = TESTING_DFLAT
#-------------------------------------------------------------------

#-------------------------------------------------------------------
#  Memory Model
#-------------------------------------------------------------------
MODEL = l
#------------------------------------------------
# NOTE: Delete the DEBUG and LINKDEBUG macros to 
# build without debugging information in the .EXE
#------------------------------------------------
DEBUG = -v
LINKDEBUG = /m /v
COMPILE = tcc $(DEBUG) -DTURBOC -D$(TESTING) -c -d -m$(MODEL)
LINK= tlink $(LINKDEBUG) $(DRIVE)\tc\lib\c0$(MODEL) 
LIBS= $(DRIVE)\tc\lib\c$(MODEL)
#------------------------------------------------

.c.obj:
    $(COMPILE) $*.c

memopad.exe : memopad.obj window.obj video.obj message.obj             \
              mouse.obj console.obj textbox.obj listbox.obj            \
              normal.obj config.obj menu.obj menubar.obj popdown.obj   \
              rect.obj applicat.obj keys.obj sysmenu.obj menus.obj     \
              editbox.obj dialogs.obj dialbox.obj button.obj           \
              fileopen.obj msgbox.obj helpbox.obj log.obj lists.obj    \
              statbar.obj decomp.obj htree.obj combobox.obj            \
              pictbox.obj calendar.obj barchart.obj clipbord.obj       \
              search.obj
    $(LINK) @memopad.lnk,$*.exe,$*,$(LIBS)

huffc.exe : huffc.obj htree.obj
    $(LINK) huffc htree,$*.exe,$*,$(LIBS)


