#-------------------------------------------------------------------
#                   D - F L A T   M A K E F I L E
#-------------------------------------------------------------------

all : memopad.exe huffc.exe

#-------------------------------------------------------------------
#  Set BORLAND_CPP = 1 to compile with Borland C++ 3.0
#  Set MSC = 1 to compile with Microsoft C
#-------------------------------------------------------------------
BORLAND_CPP = 1
MSC = 0
#------------------------------------------------
# NOTE: Set DRIVE to match where you installed your compiler
#------------------------------------------------
DRIVE = F:\COMPILER
#-------------------------------------------------------------------
#  Delete the TESTING macro to eliminate the Reload
#  Help file selection on the Help menu.
#-------------------------------------------------------------------
TESTING = TESTING_DFLAT
#-------------------------------------------------------------------
#  This macro builds the full D-Flat system with all options enabled.
#  Comment it out for a minimum system or selectively
#  comment out the #defines at the top of dflat.h.
#-------------------------------------------------------------------
FULL = BUILD_FULL_DFLAT
#-------------------------------------------------------------------

!if $(MSC) == 1

#------------------------------------------------
#  Microsoft C 6.0
#------------------------------------------------
MODEL = L
#------------------------------------------------
# NOTE: Delete the DEBUG and LINKDEBUG macros to 
# build without debugging information in the .EXE
#------------------------------------------------
DEBUG = /Zi
LINKDEBUG = /CO
COMPILE = cl $(DEBUG) /DMSC /D$(TESTING) /D$(FULL) /c /W4 /Gs /A$(MODEL)
LINK = link $(LINKDEBUG) /ST:8192
#------------------------------------------------
.c.obj:
    $(COMPILE) $*.c
!endif

!if $(BORLAND_CPP) == 1

#------------------------------------------------
#  Borland C++ 2.0
#------------------------------------------------
MODEL = l
#------------------------------------------------
# NOTE: Delete the DEBUG and LINKDEBUG macros to 
# build without debugging information in the .EXE
#------------------------------------------------
DEBUG = -v
LINKDEBUG = /m /v
#------------------------------------------------
# NOTE: Temporary file space. Change to match
#       your computer. A RAM disk works best.
#------------------------------------------------
HEADERS=e:\temp\tcdef.sym
#------------------------------------------------
COMPILE = bcc -Od $(DEBUG) -D$(TESTING) -D$(FULL) -DBCPP -c -d -m$(MODEL) -H=$(HEADERS)
LINK= tlink $(LINKDEBUG) $(DRIVE)\borlandc\lib\c0$(MODEL) 
LIBS= $(DRIVE)\borlandc\lib\c$(MODEL)
#------------------------------------------------

.c.obj:
    $(COMPILE) {$*.c }
!endif


memopad.exe : memopad.obj window.obj video.obj message.obj             \
              mouse.obj console.obj textbox.obj listbox.obj            \
              normal.obj config.obj menu.obj menubar.obj popdown.obj   \
              rect.obj applicat.obj keys.obj sysmenu.obj menus.obj     \
              editbox.obj dialogs.obj dialbox.obj button.obj           \
              fileopen.obj msgbox.obj helpbox.obj log.obj lists.obj    \
              statbar.obj decomp.obj htree.obj combobox.obj            \
              pictbox.obj calendar.obj barchart.obj clipbord.obj       \
              search.obj dfalloc.obj
!if $(MSC)
    $(LINK) @memopad.lnk,$*,$*;
!else
    $(LINK) @memopad.lnk,$*.exe,$*,$(LIBS)
!endif

huffc.exe : huffc.obj htree.obj
!if $(MSC)
    $(LINK) huffc htree,$*,$*;
!else
    $(LINK) huffc htree,$*.exe,$*,$(LIBS)
!endif

